"use client";

import React from "react";

const features = [
  {
    title: "Revenue Monitoring",
    description: "Real-time tracking of your SaaS metrics with intelligent anomaly detection.",
    gradient: "from-blue-500 to-cyan-500"
  },
  {
    title: "Issue Detection",
    description: "AI-powered monitoring that identifies problems before they impact users.",
    gradient: "from-purple-500 to-pink-500"
  },
  {
    title: "AI Fix Suggestions",
    description: "Smart recommendations to resolve issues with detailed implementation guides.",
    gradient: "from-green-500 to-emerald-500"
  },
  {
    title: "GitHub Auto PRs",
    description: "Automated pull requests generated by AI to fix your backend code.",
    gradient: "from-orange-500 to-red-500"
  },
  {
    title: "One-Click Solve",
    description: "Apply fixes instantly with a single click or review before deployment.",
    gradient: "from-indigo-500 to-purple-500"
  },
  {
    title: "Code Analysis",
    description: "Deep analysis of your codebase to identify potential improvements.",
    gradient: "from-teal-500 to-blue-500"
  }
];

export default function FeaturesSection() {
  return (
    <section className="section section-medium">
      <div className="container">
        <div className="section-header">
          <h2 className="section-title">
            Everything You Need to Protect Your SaaS
          </h2>
          <p className="section-subtitle">
            Voice2Value provides comprehensive tools to monitor, detect, and fix issues automatically.
          </p>
        </div>

        <div className="features-grid">
          {features.map((feature, index) => (
            <div
              key={index}
              className="feature-card"
            >
              <div className="feature-content">
                <div className="feature-icon">
                  <div className="feature-icon-inner"></div>
                </div>
                
                <h3 className="feature-title">
                  {feature.title}
                </h3>
                
                <p className="feature-description">
                  {feature.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
